import type { Metadata } from "next";
import {Mulish} from "next/font/google";
import "./globals.css";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

const mulish = Mulish({
  subsets: ['latin-ext'],
  variable: '--font-mulish'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={` ${mulish.variable} antialiased dark`}
      >
        
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
